services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres-supervisorio
    environment:
      - POSTGRES_DB=supervisorio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d supervisorio"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:8.4.2-alpine3.22
    container_name: redis-supervisorio
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local